baseURL = "https://trusting-kepler-0a93bf.netlify.com/"
languageCode = "en-us"
title = "yarn add --save-dev Creative-Thinking"
theme = "reveal-presentation"
[params]
description = "Description of presentation"
author = "Amos Garner"