baseURL = "https://trusting-kepler-0a93bf.netlify.com/"
languageCode = "en-us"
title = "Creative-Thinking"
theme = "reveal-presentation"
[params]
description = "Presentation on creative thinking and how it helped me overcome Imposter Syndrome."
author = "Amos Garner"
theme = "blood"